//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Draw.rc
//
#define ID_PAGE                         1
#define IDR_DRAWTYPE_SRVR_IP            4
#define IDR_DRAWTYPE_SRVR_EMB           5
#define IDR_DRAWTYPE_CNTR_IP            6
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             101
#define IDP_FAILED_TO_CREATE            102
#define IDS_MAIN_TOOLBAR                103
#define IDS_BUILD_TOOLBAR               104
#define IDS_SIMULATION_TOOLBAR          105
#define IDD_COLOURPICKDEMO_DIALOG       106
#define IDI_OK                          107
#define IDB_ARROWS                      108
#define IDR_MAINFRAME                   128
#define IDR_DRAWTYPE                    129
#define IDR_POPUP_TOOLBAR               130
#define IDR_FORMAT_TOOLBAR              131
#define IDB_WORKSPACE                   132
#define IDB_CLASS_VIEW                  133
#define IDC_USER_OBJ                    133
#define IDB_RESOURCE_VIEW               134
#define IDR_NETWORK                     135
#define IDS_INVALID_NUMBER              136
#define IDR_SIMULATION                  137
#define IDS_INVALID_FONTSIZE            137
#define IDR_UNDO                        138
#define IDB_LOGO                        139
#define IDI_RARROW                      140
#define IDI_LARROW                      141
#define IDB_IMAGES                      142
#define IDC_NODE_CURSOR                 143
#define IDD_DELETE                      145
#define IDB_BITMAP1                     146
#define IDC_HANDER                      147
#define IDR_MENU1                       148
#define IDC_ZOOMCURSOR                  149
#define IDD_PROP_RECT                   150
#define IDC_ZOOMCURSOR1                 150
#define IDD_STAT_PAGE                   151
#define IDD_SUMM_PAGE                   152
#define IDC_PENCIL                      154
#define IDD_PROJECT                     154
#define IDD_CONSTRAINT                  155
#define IDD_OBJECTIVE                   156
#define IDD_SETUP                       158
#define ID_POPUP_MENU                   162
#define IDR_DRAWCLTYPE_CNTR_IP          163
#define IDR_OUTPUT                      164
#define IDB_FONTTYPE                    165
#define IDI_ICON1                       166
#define IDB_CHECK                       166
#define IDC_FONTNAME                    167
#define IDC_FONTSIZE                    168
#define IDR_GRID                        168
#define IDD_SIMU_PAGE1                  169
#define IDD_SIMU_PAGE2                  170
#define IDD_SIMU_PAGE3                  171
#define IDD_DIALOG1                     173
#define IDD_IMM                         173
#define IDB_BITMAP2                     174
#define IDR_TOOLBAR                     175
#define IDB_B1                          175
#define IDB_B2                          176
#define IDB_FILE_VIEW                   177
#define IDI_NODE                        178
#define IDB_B3                          178
#define IDI_REGULATION                  179
#define IDB_B4                          179
#define IDI_REACTION                    180
#define IDB_B5                          180
#define IDI_SYSTEM                      181
#define IDB_B11                         181
#define IDD_LINE                        182
#define IDR_MATRIX                      182
#define IDD_NODE                        183
#define IDD_IMM2                        184
#define IDD_NMR                         185
#define IDD_REGULATION                  186
#define IDD_TEXT                        187
#define IDD_REACTION                    188
#define IDD_FLUX                        189
#define IDD_MFC                         191
#define IDD_DIALOG2                     192
#define IDR_MENU2                       193
#define IDD_DESIGNPAGE                  194
#define IDD_FLUXSEARCH                  195
#define IDD_OPTION                      196
#define IDD_VARIABLE                    197
#define IDD_PARAMETER                   198
#define IDD_KINETICS                    200
#define IDI_OPEN                        201
#define IDD_DIALOG_PATHWAY              202
#define IDD_EM                          203
#define IDC_ENZYME                      204
#define IDC_CATALYZE                    205
#define IDD_ENZYME                      206
#define IDD_FIX                         207
#define IDD_DCDT                        208
#define IDD_FIGSETUP                    209
#define IDD_MCA                         213
#define IDR_PATHWAY                     215
#define IDR_FLUX                        217
#define IDD_DIALOG4                     219
#define IDD_NMRPLUGIN                   219
#define IDD_BALANCE_SHEET               220
#define IDD_SEARCH                      221
#define IDD_DISCRETE                    222
#define IDD_DATA                        225
#define IDI_SAVE                        226
#define IDD_DIALOG5                     228
#define IDD_WIZARD                      228
#define IDD_IMMWIZARD                   228
#define IDR_POPUP_CLASS_VIEW            230
#define IDR_POPUP_OUTPUT_VIEW           231
#define IDR_POPUP_FILE_VIEW             232
#define IDD_ADD_PARAMETER               233
#define IDD_ADD_VARIABLE                234
#define IDR_POPUP_DATA_VIEW             235
#define IDD_TEXT_FORMAT                 236
#define IDD_FILL_GRADIENT               238
#define IDD_FILL_PATTERN                239
#define IDD_FILL_PICTURE                240
#define IDD_COLOR_LINE                  243
#define IDD_OPTION_VIEW                 245
#define IDD_FILL_DLG                    246
#define IDD_DIALOG3                     247
#define IDC_FILL_COLOR                  1000
#define IDC_OUTPUT                      1001
#define IDC_EDGE_COLOR                  1001
#define IDC_COLOURPICKER                1002
#define IDC_LINE_COLOR                  1003
#define IDC_WEIGHT                      1004
#define IDC_MODE1                       1005
#define IDC_FILL                        1006
#define IDC_MODE2                       1007
#define IDC_SET_DEFAULT                 1008
#define IDC_SPIN1                       1009
#define IDC_TRACK                       1010
#define IDC_SET_DEFAULT2                1010
#define IDC_SPIN2                       1011
#define IDC_NOFILL                      1012
#define IDC_DISABLE                     1013
#define IDC_SPIN5                       1013
#define IDC_SAVEDBY                     1014
#define IDC_DEFAULT_EDIT                1015
#define IDC_LIST_LINE_STYLE1            1016
#define IDC_REVNUM                      1017
#define IDC_CUSTOM_EDIT                 1018
#define IDC_EDITTIME                    1019
#define IDC_SPIN4                       1020
#define IDC_LASTPRINT                   1021
#define IDC_SPIN3                       1022
#define IDC_CREATEDATE                  1023
#define IDC_ARROW_START                 1024
#define IDC_NUMPAGES                    1025
#define IDC_ARROW_END                   1026
#define IDC_NUMWORDS                    1027
#define IDC_BA_REACTANT                 1028
#define IDC_NUMCHARS                    1029
#define IDC_WWW                         1030
#define IDC_SECURITY                    1031
#define IDC_EMAIL                       1032
#define IDC_EDIT14                      1032
#define IDC_LASTSAVE                    1033
#define IDC_VERSION                     1034
#define IDC_FILLNOLINEAR                1034
#define IDC_APPNAME                     1035
#define IDC_FILLEVEN                    1035
#define IDC_FRIENDS                     1036
#define IDC_FILLLINEAR                  1036
#define IDC_AUTHOR                      1037
#define IDC_NADTH                       1037
#define IDC_DILUTE                      1037
#define IDC_LINEPICKER                  1038
#define IDC_ATP                         1038
#define IDC_LIST_LINE_STYLE             1039
#define IDC_RATE                        1039
#define IDC_KEYWORDS                    1040
#define IDC_PROJECT_TYPE                1040
#define IDC_ARROW_START_SIZE            1041
#define IDC_RADIO4                      1041
#define IDC_LIST_LINE_COLOR             1042
#define IDC_COMMENTS                    1043
#define IDC_ARROW_END_SIZE              1044
#define IDC_GAMS_DIR                    1044
#define IDC_LINE_SIZE                   1045
#define IDC_TITLE                       1046
#define IDC_TEXT_ALLIGNMENT             1047
#define IDC_LIST_FILL_COLOR             1048
#define IDC_SUBJECT                     1049
#define IDC_CULTURE_TIME                1049
#define IDC_FONT_COLOR                  1050
#define IDC_TEXT_ALLIGNMENT2            1051
#define IDC_START_TIME                  1051
#define IDC_CHECK1                      1052
#define IDC_DILUTE_RATE                 1052
#define IDC_TEMPLATE                    1053
#define IDC_CULTURE_TYPE                1053
#define IDC_TEXT_INPUT                  1054
#define IDC_IMM                         1054
#define IDC_LIST_ARROW_STYLE            1055
#define IDC_BORDER                      1056
#define IDC_ARROW_SIZE                  1057
#define IDC_ROUND_PEN                   1058
#define IDC_MATRIXBAR_LOCATION          1058
#define IDC_CHECK2                      1059
#define IDC_COMBO_CAPTION               1060
#define IDC_CAPTION                     1060
#define IDC_BOUND                       1060
#define IDC_CHECK5                      1060
#define IDC_COMBO2                      1061
#define IDC_RADIO3                      1061
#define IDC_COMBO3                      1062
#define IDC_EDIT_UB                     1062
#define IDC_COMBO_TYPE                  1063
#define IDC_RADIO_SEARCH                1063
#define IDC_EDIT_LB                     1063
#define IDC_NODE_BORDER                 1064
#define IDC_CHECK4                      1064
#define IDC_RICHEDIT2                   1065
#define IDC_EDIT_SYMBOL                 1066
#define IDC_ADDV                        1066
#define IDC_LIST1                       1067
#define IDC_EDIT_SYMBOL2                1067
#define IDC_DELETEV                     1067
#define IDC_EDIT_NOTE                   1068
#define IDC_MW                          1069
#define IDC_LIST2                       1070
#define IDC_EDIT_FORMULA                1071
#define IDC_LIST3                       1072
#define IDC_CUSTOM1                     1073
#define IDC_CONSTRAINT                  1073
#define IDC_GRID                        1074
#define IDC_LIST4                       1075
#define IDC_BUTTON1                     1076
#define IDC_RADIO5                      1076
#define IDC_BUTTON2                     1077
#define ID_ADVANCE                      1077
#define IDC_NAME                        1077
#define IDC_BR_REACTANT                 1078
#define IDC_SYMBOL                      1078
#define IDC_BUTTON8                     1078
#define IDC_BUTTON3                     1079
#define IDC_EXPRESSION                  1079
#define IDC_CANCEL                      1080
#define IDC_BUTTON9                     1080
#define IDC_BUTTON4                     1081
#define IDC_BA_PRODUCT                  1082
#define IDC_BUTTON10                    1082
#define IDC_BUTTON5                     1083
#define IDC_ADDP                        1083
#define IDC_BR_PRODUCT                  1084
#define IDC_EDIT_ENZYME                 1084
#define IDC_BUTTON11                    1084
#define IDC_BUTTON6                     1085
#define IDC_DELETEP                     1085
#define IDC_TEXT_STRIKE                 1086
#define IDC_EDIT4                       1086
#define IDC_BUTTON7                     1087
#define IDC_DB1                         1088
#define IDC_EDIT3                       1088
#define IDC_EC                          1088
#define IDC_TEXT_UNDER                  1089
#define IDC_LINE_STYLE                  1089
#define IDC_RICHEDIT1                   1090
#define IDC_LINE_WIDTH                  1090
#define IDC_RICHEDIT3                   1091
#define IDC_REMOVE                      1091
#define IDC_COMBO1                      1092
#define IDC_VARLIST                     1092
#define IDC_COMBO4                      1093
#define IDC_COMBO_SOLVER                1093
#define IDC_EDIT1                       1094
#define IDC_RADIO1                      1095
#define IDC_MARK_SIZE                   1095
#define IDC_FULLNAME                    1095
#define IDC_EDIT10                      1095
#define IDC_RADIO2                      1096
#define IDC_EDIT_PEAK                   1096
#define IDC_EDIT11                      1096
#define IDC_CHECK3                      1097
#define IDC_END_TIME                    1097
#define IDC_COMBO_PLUGIN                1097
#define IDC_RADIO6                      1097
#define IDC_EDIT5                       1097
#define IDC_EDIT2                       1098
#define IDC_BUTTON_ADD                  1098
#define IDC_FONT                        1099
#define IDC_EDIT_GRAPH                  1099
#define IDC_FONT_STYLE                  1100
#define IDC_EDIT_PEAK_ONLY              1100
#define IDC_EDIT_AUTHER                 1101
#define IDC_BUTTON_DELETE               1102
#define IDC_BALANCE_SHEET               1103
#define IDC_EDIT_EMAIL                  1104
#define IDC_TARGET                      1104
#define IDC_EDIT_SIGNAL                 1105
#define IDC_CHECK_CASE                  1105
#define IDC_SYNONYM                     1106
#define IDC_RADIO7                      1107
#define IDC_RADIO8                      1108
#define IDC_RADIO9                      1109
#define IDC_SCROLLBAR1                  1111
#define IDC_SCROLLBAR2                  1112
#define IDC_SCROLLBAR4                  1114
#define IDC_TAB1                        1116
#define IDC_STATIC2                     1117
#define IDC_STATIC1                     1118
#define IDC_SAMPLE                      1121
#define IDC_STATICNAME                  1123
#define ID_CANCEL_EDIT_SRVR             31811
#define ID_VIEW_WATCH                   31821
#define ID_VIEW_SIMULATION              31823
#define ID_OBJECT_FILLCOLOR             31830
#define ID_OBJECT_LINECOLOR             31831
#define ID_CHAR_COLOR                   31840
#define ID_FILL_COLOR                   31841
#define ID_LINE_COLOR                   31842
#define ID_LINE_WIDTH                   31843
#define ID_LINE_STYPE                   31844
#define ID_ARROW_STYLE                  31845
#define ID_LEFTARROW_STYLE              31845
#define ID_DRAW_TEXT                    31846
#define ID_ADD_REACTANT                 31850
#define ID_ADD_REACTION                 31851
#define ID_ADD_REGULATION               31852
#define ID_ADD_VARIABLE                 31852
#define ID_LINEWIDTH0                   31885
#define ID_LINEWIDTH1                   31886
#define ID_LINEWIDTH2                   31887
#define ID_LINEWIDTH3                   31888
#define ID_LINEWIDTH4                   31889
#define ID_LINEWIDTH5                   31890
#define ID_LINEWIDTH6                   31891
#define ID_LINEWIDTH7                   31892
#define ID_LINEWIDTH8                   31893
#define ID_LINESTYLE0                   31900
#define ID_LINESTYLE1                   31901
#define ID_LINESTYLE2                   31902
#define ID_LINESTYLE3                   31903
#define ID_LINESTYLE4                   31904
#define ID_LINESTYLE5                   31905
#define ID_LINESTYLE6                   31906
#define ID_LINESTYLE7                   31907
#define ID_LINESTYLE8                   31908
#define ID_LEFTARROW0                   31910
#define ID_LEFTARROW1                   31911
#define ID_LEFTARROW2                   31912
#define ID_LEFTARROW3                   31913
#define ID_LEFTARROW4                   31914
#define ID_LEFTARROW5                   31915
#define ID_RIGHTARROW0                  31920
#define ID_RIGHTARROW1                  31921
#define ID_RIGHTARROW2                  31922
#define ID_RIGHTARROW3                  31923
#define ID_RIGHTARROW4                  31924
#define ID_RIGHTARROW5                  31925
#define ID_VIEW_PAPERCOLOR              32583
#define ID_EDITPROPERTY                 32680
#define ID_NEWPARAMETER                 32681
#define ID_DELETE                       32682
#define ID_NEWVARIABLE                  32683
#define ID_VIEW_TOOLBARS                32700
#define ID_VIEW_USER_TOOLBAR1           32761
#define ID_VIEW_USER_TOOLBAR2           32762
#define ID_VIEW_USER_TOOLBAR3           32763
#define ID_DRAW_ELLIPSE                 32764
#define ID_VIEW_USER_TOOLBAR5           32765
#define ID_VIEW_USER_TOOLBAR6           32766
#define ID_OBJECT_MOVETOFRONT           32767
#define ID_CANCEL_EDIT                  32768
#define ID_VIEW_GRID                    32769
#define ID_DRAW_SELECT                  32770
#define ID_DRAW_LINE                    32771
#define ID_DRAW_RECT                    32772
#define ID_DRAW_ROUNDRECT               32773
#define ID_VIEW_USER_TOOLBAR4           32774
#define ID_VIEW_USER_TOOLBAR7           32777
#define ID_OBJECT_MOVETOBACK            32778
#define ID_VIEW_USER_TOOLBAR8           32779
#define ID_OBJECT_MOVEFORWARD           32780
#define ID_VIEW_USER_TOOLBAR9           32781
#define ID_OBJECT_MOVEBACK              32782
#define ID_VIEW_USER_TOOLBAR10          32784
#define ID_DRAW_POLYGON                 32785
#define ID_VIEW_OUTPUT                  32786
#define ID_VIEW_SHOWOBJECTS             32787
#define ID_EDIT_PROPERTIES              32788
#define ID_SIMULATION_STEP              32789
#define ID_DUMMY_COMPILE                32790
#define ID_DUMMY_BUILD                  32791
#define ID_TOOL_BUILD                   32791
#define ID_SUMULATION_RUN               32792
#define ID_DUMMY_EXECUTE                32793
#define ID_DUMMY_GO                     32794
#define ID_SIMULATION_PAUSE             32795
#define ID_FILE_SUMMARYINFO             32796
#define ID_SIMULATION_STOP              32797
#define ID_DRAW_ARROW                   32798
#define ID_DUMMY_SELECT_ACTIVE_CONFIGURATION 32799
#define ID_SIMUATION_FLUX               32800
#define ID_SIMULATION_MFC               32801
#define ID_VIEW_BUILD_TOOLBAR           32802
#define IDC_SIMULATE                    32803
#define IDC_FLUX                        32804
#define IDC_MCA                         32805
#define ID_TOOL_MCA                     32805
#define ID_EDIT_UNDO_DUMMY              32806
#define ID_EDIT_UNDO1                   32806
#define IDS_DUMMY_UNDO_ACTION           32807
#define IDC_ADD_REACTANT                32808
#define IDC_ADD_REACTION                32809
#define IDC_ADD_REGULATION              32810
#define IDC_ADD                         32811
#define ID_EDIT_DELETE                  32812
#define ID_EDIT_SELECTALL               32813
#define ID_EDIT_CLEARALL                32814
#define ID_EDIT_GROUP                   32815
#define ID_EDIT_UNGROUP                 32816
#define ID_CANCEL_EDIT_CNTR             32817
#define ID_VIEW_ZOOM_50                 32817
#define ID_VIEW_ZOOM_100                32818
#define ID_BUILD_DUMP                   32819
#define ID_TOOL_FLUXOPTIMIZATION        32820
#define ID_TOOL_EZYMEPROFILEOPTIMIZATION 32821
#define ID_TOOL_TOPLOGICALANALYISIS     32822
#define IDC_TOOLBAR_MAIN                32823
#define ID_VIEW_ZOOM_75                 32823
#define IDC_TOOLBAR_NETWORK             32824
#define ID_TOOL_FLUX                    32824
#define IDC_TOOLBAR_SIMULATION          32825
#define ID_TOOL_SIMULATE                32825
#define ID_VIEW_CUSTOMIZE               32826
#define ID_VIEW_WORKSPACE               32827
#define ID_ZOOM_IN                      32829
#define ID_ZOOM_OUT                     32830
#define ID_ZOOM_FULL                    32831
#define ID_FILE_OPTION                  32832
#define ID_VIEW_FLUX                    32833
#define ID_TOOL_NMR                     32836
#define ID_TOOL_CHECK                   32839
#define ID_DUMMY_CLEAR                  32842
#define ID__CLEARALL                    32843
#define ID_DUMMY_CLEARALL               32844
#define ID_ADD_CONTSTAINT               32849
#define ID_DELETE_CONSTRAINT            32850
#define ID_TOOL_FLUXOPTIMIZATION_ONESOLUTION 32851
#define ID_TOOL_FLUXOPTIMIZATION_ALLSOLUTION 32852
#define ID_MODE_STOICHIOMETRIC          32855
#define ID_MODE_KINECTICMODEL           32856
#define ID_BUTTON1                      32857
#define ID_BUTTON2                      32858
#define ID_BUTTON3                      32859
#define ID_BUTTON32860                  32860
#define ID_BUTTON32861                  32861
#define ID_BUTTON32862                  32862
#define ID_BUTTON6                      32863
#define ID_BUTTON5                      32864
#define ID_BUTTON4                      32865
#define ID_MATRIX_OPEN                  32867
#define ID_MATRIX_SAVE                  32868
#define ID_CLEAR_USER                   32869
#define ID_BUILD_CLEARALLIMM            32870
#define ID_GRID_DELETEALL               32871
#define ID_EDIT_RESETFLUXTEXTBOX        32872
#define ID__COPYALL                     32874
#define ID_OUTPUT_COPY                  32875
#define ID_OUTPUT_COPYALL               32876
#define ID_OUTPUT_CLEAR                 32877
#define ID_OUTPUT_CLEARALL              32878
#define ID_BUILD_EXPORT_REACTIONS       32879
#define ID_BUILD_EXPORT_FLUXES          32880
#define ID_BUILD_EXPORT_RESULT          32881
#define ID_BUILD_EXPORT_CODE            32882
#define ID_TOO_INFO                     32883
#define ID_TOOL_INFO                    32884
#define ID_COLORPOPUP_C                 32903
#define ID_RIGHTARROW_STYLE             32914
#define ID_ADDCONSTANT                  32915
#define ID_ADD_PARAMETER                32916
#define ID_OUTPUT_EDITCODE              32917
#define ID_NMR_DESIGN                   32918
#define ID_NMR_SEARCH                   32919
#define ID_SHOW_PATH                    32923
#define ID_VIEW_EMPROPERTIES            32926
#define ID_BUILD_EXPORTEM               32927
#define ID_ADDENZYME                    32928
#define ID_ADD_CATALYZE                 32929
#define ID_BUILD_MODE_KINETICMODELINCLUDETRANSLATIONANDTRANSCRIPTION 32930
#define ID_BUTTON32931                  32931
#define ID_SIMULATION_MCA               32933
#define ID_NEXT_PATHWAY                 32938
#define ID_PREV_PATHWAY                 32941
#define ID_PREV_FLUX                    32942
#define ID_NEXT_FLUX                    32943
#define ID_VIEW_PATHWAY_TOOLBAR         32944
#define ID_VIEW_FLUX_TOOLBAR            32945
#define ID_ADD_PAGE                     32946
#define ID_REMOVE_PAGE                  32947
#define ID_NEXT_PAGE                    32948
#define ID_PAGE_PREVIOUS                32949
#define ID_EDIT_UNDO2                   32950
#define ID_BUILD_CELLBALANCESHEET       32967
#define ID_EDIT_SEARCH                  32968
#define ID_BUILD_EXPORT_CONSTRAINTS     32969
#define ID_VIEW_TABLEVIEW               32970
#define ID_VIEW_NETWORKVIEW             32971
#define ID_DRAW_SCRIBBLE                32972
#define ID_DRAW_CURVE                   32973
#define ID_WIZARD                       32974
#define ID__COPY                        32975
#define ID__PASTE                       32976
#define ID_CON_COPY                     32977
#define ID_CON_PASTE                    32978
#define ID__ADDAFIGURE                  32984
#define ID__ADDATABLE                   32985
#define ID__OPENEDIT                    32986
#define ID__DELETE                      32987
#define ID_POPUP_OPENFILE               32988
#define ID_ADD_DDATATABLE               32992
#define ID_ENTERDATA                    32993
#define ID_DELETEDATATABLE              32994
#define ID_DRAW_CLOSEDCURVE             32995
#define ID_EDIT_FIND_COMBO              57902
#define ID_VIEW_FORMAT_TOOLBAR          59396
#define ID_COLOR_TEAROFF                61446
#define IDP_BUSY                        61447
#define IDS_HEADLINE_NMR                61447
#define IDS_HEADLINE2                   61448
#define IDS_HEADLINE0                   61449
#define ID_ACTION_ADD_COMMON            61450
#define ID_ACTION_ADD_REACTION          61451
#define ID_ACTION_ADD_CATALYZE          61452
#define ID_ACTION_SIZE                  61453
#define ID_ACTION_MOVE                  61454
#define ID_ACTION_ADDPOLY               61455
#define ID_ACTION_ADD_NODE              61456
#define ID_ACTION_ADD_ENZYME            61457
#define ID_ACTION_ADD_BRANCH            61458
#define ID_ACTION_SIZE_REACTION         61459
#define ID_ACTION_REMOVE_BRANCH         61460
#define ID_ACTION_DELETE_REACTION       61461
#define ID_ACTION_EDIT                  61462
#define ID_ACTION_EDIT_REACTION         61463
#define ID_ACTION_MOVE_POSITION         61464
#define ID_ACTION_LEFT_ARROW            61465
#define ID_ACTION_RIGHT_ARROW           61466
#define ID_ACTION_COLOR_LINE            61467
#define ID_ACTION_COLOR_FILL            61468
#define ID_ACTION_COLOR_TEXT            61469
#define ID_ACTION_LINE_SIZE             61470
#define ID_ACTION_LINE_STYLE            61471
#define ID_ACTION_FONT                  61472
#define ID_ACTION_DELETE                61473
#define ID_ACTION_PASTE                 61474
#define ID_ACTION_EDIT_MULTI            61475
#define ID_ACTION_FLUX                  61476
#define ID_ACTION_PAGE_ADD              61477
#define ID_ACTION_PAGE_DELETE           61478
#define ID_ACTION_MOVE_ONE              61479
#define IDS_HEADLINE_MS                 61480
#define IDS_DEFAULTFONT                 61481
#define ID_ACTION_SIZE_REGULATION       61482
#define ID_ACTION_EDIT_REGULATION       61483

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        248
#define _APS_NEXT_COMMAND_VALUE         32997
#define _APS_NEXT_CONTROL_VALUE         1124
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
